name:                while
version:             0.1.0.0
github:              "jeffhappily/while"
license:             BSD3
author:              "Jeff"
maintainer:          "example@example.com"
copyright:           "2020 Jeff"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeffhappily/while#readme>

ghc-options:
- -Wall
- -fwarn-tabs

dependencies:
- base >= 4.7 && < 5
- transformers

library:
  source-dirs: src

executables:
  while-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - while

tests:
  while-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - while
